### ISSUE TITLE
Libvirt Service failed to start.

### ISSUE THREAD

**Issue by kelefy** [EideardVMR/unraid-easybackup#1]
Hit this issue on my unraid:

![屏幕截图 2023-09-21 075417](https://github.com/EideardVMR/unraid-easybackup/assets/7692927/e8e555ac-ed31-4a53-a775-c02d7266c21f)

**Comment by EideardVMR** [comment]
Hi, thanks for your feedback.
Is your VM service active? Currently the plugin only works when VM service and Docker service are started. 

If you are sure that the service is started, then restart it once. 

Which Unraid version do you have installed?

**Comment by kelefy** [comment]
Hi, EideardVMR
Problem sovled when i start the VM service
many thanks for you help.

**Comment by EideardVMR** [comment]
all clear! Thank you. I will consider this case in one of the future versions.

Do you have problems to see the settings? I received this error message but can't reproduce it so far. On my test systems this does not occur.

**Comment by kelefy** [comment]
you can try to remove this file, and stop the VM service
/mnt/user/system/libvirt/libvirt.img

**Comment by EideardVMR** [comment]
why should i do that?
This file is important for the virtualization environment.
Easybackup does not independently delete files outside of its own two folders or the folders you have configured.

All deleted files are moved to the recycle bin if configured. 
Exceptions: 
- temporarily created files when creating backups
- snapshot files
