### ISSUE TITLE
Plugin text dosn't correctly display when unraid is using the 'black' base theme.

### ISSUE THREAD

**Issue by thestraycat** [EideardVMR/unraid-easybackup#6]
As above really. (Running Unraid 6.12.4)

Changing it back to 'white' base theme displays correctly. But dark mode is very popular and it would be awesome if it could support it... assuming it's just the property of the text colour in some way?

**Unraid Theme options**

![image](https://github.com/EideardVMR/unraid-easybackup/assets/9296295/ade8eab3-1c7b-422e-8aed-9a3fa2b3ef4c)

**Black Base Theme - Turned on.**

![image](https://github.com/EideardVMR/unraid-easybackup/assets/9296295/2121e564-61b8-4075-baa6-4e3b818c8729)

**Highlighting the invisible text shows the text is present still.**

![image](https://github.com/EideardVMR/unraid-easybackup/assets/9296295/c13d7fab-d9eb-4cfe-af74-4ff09692a493)

**Comment by EideardVMR** [comment]
Hi, thank you. 
The error is known. In the next version the color will be fixed in the box. With the table, I also still have an unsightly color effect in the Azure and White design.

I myself have been using the Gray design for years and haven't even thought about the fact that you can change it. 

But I ask for a little patience. It will be fixed in the next patch!

**Comment by thestraycat** [comment]
No worries! Glad you'd seen it.

I also noticed that when you disable container backup, it says "VM Backup is Disabled" 
![image](https://github.com/EideardVMR/unraid-easybackup/assets/9296295/48a32fac-d4c7-4595-a150-4fb798dafc5c)

Lastly, You might want to add a description and start your own unraid support page? (Currently your support link goes to [PLUGIN] CA USER SCRIPTS support page, assuming you used it as a template when authoring the plugin?) But having your own may help to condense the feedback to one place? Just a thought.  Keep up the good work though! I have no idea why unraid dosn't have this functionality integrated along with snapshotting... Such a shame. :(

![image](https://github.com/EideardVMR/unraid-easybackup/assets/9296295/6c15dca7-8d9b-430e-b41f-1332f9e81c03)

**Comment by EideardVMR** [comment]
Oh this is probably a copy & paste error ^^ 
I change the same with ;) 

As for the description and also the support link...
I am a little disappointed. The documentation on how to properly create a plugin and integrate you have to find many different sources together and many of them are outdated.

I have created a support forum. Marked this as hidden, can't see it myself and also can't open it. Have therefore asked the moderator. Unfortunately nothing happened. A description is also available in the XML one has to submit. But how do I get this now in the plugin.... I have no idea! 

![image](https://github.com/EideardVMR/unraid-easybackup/assets/143615696/a2e20ea6-74e9-47fb-87f5-c0a94a8b852c)

After in the forum some have expressed your displeasure about the plugin and then wrongly a warning message was added to the plugin that it allegedly leads to the fact that the whole server could crash. Thus, I was a bit frustrated and told myself I'll do the support here.

I'm sorry, I would also like a forum there. But I will remain active here!

It is my first and probably my last plugin for Unraid.

**Comment by EideardVMR** [comment]
Hey, good news. I am planning a patch for Sunday 29.10.2023
Current tests are going well, unless something unexpected goes wrong by then I will upload the patch and your problem will be fixed here as well.

**Comment by thestraycat** [comment]
Fantastic - I'll take a look! 

- In regards to the plugin XML i know the formatting can be very picky and cause issues with certain fields populating might be worth checking?
- In regards to the forum, i wouldnt take it personally, it's probably just worth explaining why that person may have had an issue, afterall the plugin will never get good exposure or be trusted without the community behind it and it deserves to be used as it's an incredibly useful plugin!! I'd urge you to at try the forum... there not a bad bunch! And everyone could benefit from your skills...

**Comment by EideardVMR** [comment]
I will wait a little until I can be quite sure that all the current functions really work, then I will ask the moderators to add the plugin again, with a support link. Until then, I will check the forum sporadically.

I still need to restore the backups and shorten the loading times.

**Comment by thestraycat** [comment]
Sounds like a plan! - And just to confirm, you resolved the text issue for me when using a dark theme. So thank you!
